apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}-{{ .Values.enviroment }}-config"
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.port }}"
  TARGET_PORT: "{{ .Values.targetPort }}"