apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-{{ .Values.enviroment }}-deployment"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-{{ .Values.enviroment }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}-{{ .Values.enviroment }}"
    spec:
      containers:
      - name: "{{ .Values.appName }}-{{ .Values.enviroment }}-container"
        image: "{{ .Values.image.repository }}/{{ .Values.image.imageName }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}
