apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-{{ .Values.enviroment }}-service"
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.appName }}-{{ .Values.enviroment }}"
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
